### ISSUE TITLE
[Issue] Timber enchant

### ISSUE THREAD

**Issue by WarnDangerous** [GC-spigot/AdvancedEnchantments#1269]
**Describe the bug**
- It doesn't work with JobsReborn ( or it's very bugged )
- It doesn't detect if it's a tree or just a player build ( build an house ), and it breaks EVERY log !

**Ideas**
- Add an animation like the other timber plugin ( that you may know )
- Add a way for the plugin to also decay leaves and drop saplings
- Auto replant saplings when you break a tree

**Server Information (please complete the following information):**
 - Paper 1.12.2
- AdvancedEnchant 7.9.37

**Comment by GC-spigot** [comment]
It’s nowhere mentioned to have support for JobsReborn

There is no possible way to “detect” a tree or a player placed block, they are the same. I can’t log every player placed block, can’t have pre-defined tree patterns as there’s custom gen plugins which would cause issues along with a huge list of other issues that could arise together. Sadly it will break every tree block as it’s meant to do that because there’s no alternative.

**Comment by WarnDangerous** [comment]
So would it be possible to add support for JobsReborn ? ( I thought it was supported )

**Comment by WarnDangerous** [comment]
And I tried the other plugin (songoda one), they detect fine if it's a tree or a player construct, and they also got fancy animation, maybe try to see how they did and make something similar ?

**Comment by GC-spigot** [comment]
They log all player placed blocks, and I’m not going to be doing that for one effect

**Comment by EnderGamingFilms** [comment]
You could use CoreProtect as a softDepend to do this. Their api is decent.
