### ISSUE TITLE
Add/Create a tutorial for creating enchants [Request]

### ISSUE THREAD

**Issue by BusterBoys** [GC-spigot/AdvancedEnchantments#1589]
I have had trouble with creating a sword enchant that increases the damage of the sword (its basicly a better version of sharpness)
and im not sure how to use some of the enchantment effects

**Comment by KasearMC** [comment]
i second this. apparently i don't know how to use this plugin at all because i can't get any enchants to work.
i'm creating my own groups and enchants but nothing seems to be working. if i'm doing something wrong, i don't know where to find that out.
at this point it feels more like a guessing game.

**Comment by BusterBoys** [comment]
Yea and its starting to annoy me bc i have a server im trying to make custom enchants for so its rlly annoying at this point

**Comment by Insprill** [comment]
@MamboTND is working on tutorials :) you can you our [Discord Server](https://discord.gg/GzdQdMw) for updates
