### ISSUE TITLE
[Issue] Never gets a custom enchantment in enchanting table

### ISSUE THREAD

**Issue by 6u5t4v** [GC-spigot/AdvancedEnchantments#1637]
**Describe the bug**
I never get a custom enchantment when enchanting inside enchanting table, I have enabled it inside the enchantmentTable.yml, I have enchanted an item 50+ times.

EDIT just notice I'd got this error https://pastebin.com/z7WxV77P

**To Reproduce**
Litteraly just enchant an item inside enchanting table.

**Server Information (please complete the following information):**
- Server Version: git-Paper-403 (MC: 1.16.4)
- Plugin Version: 8.0.0-Pre17.1

**Comment by RulerOfEternity** [comment]
Umm to be honest I don't know if this is fixed but I noticed you're running an out-dated version of the plugin, on Spigot it is the latest version, however, the developer was locked out of it and he's providing license transfers to his own website, you can ask for a transfer but it might take a while since he has exams I believe and there are a lot of requests, you can request for a license transfer on his Discord by opening a ticket and showing proof that you own it. His discord is here: https://discord.gg/tm9QzqvmQA

**Comment by RulerOfEternity** [comment]
You can also try increasing the probability of the enchant appearing in the Configuration file.

**Comment by 6u5t4v** [comment]
> Umm to be honest I don't know if this is fixed but I noticed you're running an out-dated version of the plugin, on Spigot it is the latest version, however, the developer was locked out of it and he's providing license transfers to his own website, you can ask for a transfer but it might take a while since he has exams I believe and there are a lot of requests, you can request for a license transfer on his Discord by opening a ticket and showing proof that you own it. His discord is here: https://discord.gg/tm9QzqvmQA

I have already requested.



> You can also try increasing the probability of the enchant appearing in the Configuration file.

I have tried that, It still doesnt work.
