### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by driftwould** [GC-spigot/AdvancedEnchantments#1648]
**Describe the bug**
I really just want to make it so that other plugins like crazy envoy or mythicmobs can drop items with the custom enchantment. I am new to plugins but from what I have heard all I need to do is put the enchantment name in the lore however that doesn't work. I have tried to use the discord but never get an answer only someone who just asks another question. Please help me. I haven't even been able to use the plugin once. Im not sure if this is the right place to ask but I can't fine anywhere else to ask.

**Server Information (please complete the following information):**
- Server Version: paperspigot 1.16.4
- Plugin Version: 8.0.0-pre17.6

**Comment by GC-spigot** [comment]
Hi, so the issue is that AdvancedEnchantments uses NBT (internal item data) and simply adding lore will not work - this is the only limitation of our system, but using NBT lets us do what normally would be impossible.

I recommend using commands with those plugins to give books or items (you can give custom enchanted items using /aegive)
