### ISSUE TITLE
Breaking chests with a tool that has Telepathy enchant destroys the contents when using use-experimental-block-breaking

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#1849]
## Details

**Describe the bug**
If you break a chest (with items inside it) with a tool that has Telepathy, the items inside will be destroyed if `use-experimental-block-breaking` is set to true.

**To Reproduce**
1.) Set `use-experimental-block-breaking` to true.
2.) Fill a chest with items
3.) Hold an axe (or other tool) and do /ae enchant telepathy 4
4.) Use the aforementioned tool to break the chest. You will get the chest, but the items inside will disappear

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/vivugemupu
- Server log: https://gist.github.com/WhatsTheBadNews/ce5c366f0f6369d96687e8709e134e82

**Comment by nivcoo** [comment]
I have the same issue but i've disabled telepathy on chest, i think it's the same issue of https://github.com/GC-spigot/AdvancedEnchantments/issues/1850 because of the 2 issues drop items that are not the broken block. 
If you want a temporary solution : https://pics.revolis.fr/2021-04/07/08-45_7Kkb.png

**Comment by Insprill** [comment]
Fixed for pre 22.5
