### ISSUE TITLE
Execute cmds ad OP

### ISSUE THREAD

**Issue by BitNet283** [GC-spigot/AdvancedEnchantments#1888]
## Request

**Description**
Add the feature, that cmds can be executed as op players

**How the feature is useful**
Execute op cmds without giving the player op permissions

**Comment by RulerOfEternity** [comment]
If possible I'd like to have ':''s compatible in the effect line too like so:
OP: summon TNT ~ ~ ~ {Fuse:80b}

**Comment by RulerOfEternity** [comment]
This effect is vital for the success and simplification of many enchantment ideas, as of writing this I have to use an annoyingly long command string to tell the console to execute a command as a player, and even then there are some stuff that don't work the way I want them to, for example I want to make an enchantment that shows a player specific information that they otherwise wouldn't be able to see without OP permissions, when I tried that it printed the information in the CONSOLE, not the player's chat, so that's why in a nutshell I find this feature request one of the most extremely important ones out there.
