### ISSUE TITLE
Grinder & Item Drop Problem

### ISSUE THREAD

**Issue by geumu** [GC-spigot/AdvancedEnchantments#1910]
**Bukkit**: SSspigot 1.16.5
**Plugin**: AdvancedEnchantments-8.0.0-Pre21.7
**Explanation**: When you use the Grider, items fall right to the ground.
**Video**: https://youtu.be/8QaIITKAAvA

**Comment by Insprill** [comment]
Please fill out the template instead of replacing it. Try updating AE and if it's still an issue try it on a test server with only ae then add your plugin one by one to see which one is causing it. if it happens with just ae on the latest version, try on regular spigot/paper, then come back and create a new issue with your findings
