### ISSUE TITLE
Enchants not added in plugin 

### ISSUE THREAD

**Issue by CreeperMan72** [GC-spigot/AdvancedEnchantments#219]
Hello, 

I've come across a couple key enchants that are not added to the latest version. Aegis, Lucky, and Deep Wounds are not in the latest version of your plugin. Here are the descriptions of what they do. They are added on your server fantasy, so if you can add them to your plugin it would be great help!

Aegis - https://prnt.sc/lltnpf
Lucky - https://prnt.sc/lltng6 
Deep Wounds - https://prnt.sc/lltnw5

**Comment by GC-spigot** [comment]
I do not manage enchants on fantasy. They use a completely different configuration VS default one that comes with plugin, although enchant names are the same, everything else is much different.
Certain enchants are not added because they aren't possible at current state of the plugin.

What version of minecraft are you running? Guardians & Undead Ruse work on spigot1.8.8/taco 1.8.8 & paper 1.8.8
