### ISSUE TITLE
/heal command bug in AE

### ISSUE THREAD

**Issue by SenPr** [GC-spigot/AdvancedEnchantments#2296]
## Details

**Describe the bug**
AE has a /heal command that I was not made aware of. Took some time to identify. The command would return "Unknown command", but it still works. Similar to a closed issue #2192 
Don't know why this is a thing, and how it came back.

**To Reproduce** 
Take some damage, and just use /heal without permission.

**Screenshots / Video**
no screen shot or video.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/aholacumow
- Server log: no errors in logs

**Comment by SenPr** [comment]
Will also add that the command works even when a plugin such as CombatLogX blocks commands.

**Comment by denisdnu** [comment]
Сurrently, heal command is handled even if an event was canceled.
We use CombatLogX to disable heal command, it cancels the event and also restricts flight in combat, but due to handling all events (including cancelled) enchantment effects are applied and players can fly when they have Wings enchantment on their boots.

**Comment by Insprill** [comment]
Fixed in the next update. Set `settings.heal-check` to false in the config to fix it until then.
