### ISSUE TITLE
Big condition list bug

### ISSUE THREAD

**Issue by LuluxClient** [GC-spigot/AdvancedEnchantments#2323]
## Details

**Describe the bug**

If you have a long condition list, the condition of the enchant won't work
**To Reproduce** 

Try this enchantement : https://paste.md-5.net/vafocoqedo.sql 

At level 1 it will work and at level 2 it won't. 
**Screenshots / Video**

Don't need.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/onifolugap.css
- Server log: no errors

**Comment by Insprill** [comment]
That's not a bug, that's down to how you wrote the conditions. For that to work, the block type would need to be all of those blocks at the same time since each line is parsed separately from top-down. So it would first see if it's IRON_ORE, and if it's not it would stop. If it was, it would go to the next line and see if it's GOLD_ORE and since it's iron it would stop; you get the point. What you need to do is use `and` (or `&&`) statements. So it would look like `%block type% != IRON_ORE && %block type% != GOLD_ORE && %block type% != REDSTONE_ORE : %stop%`.
