### ISSUE TITLE
AdvancedEnchantments-8.6.13 bug all chestplate armor

### ISSUE THREAD

**Issue by l3unnyAnoF4** [GC-spigot/AdvancedEnchantments#2353]
### Describe the bug

https://streamable.com/pfqxvb

### How to reproduce

https://streamable.com/pfqxvb

### Screenshots / Videos

https://streamable.com/pfqxvb

### "/ae plinfo" link

https://paste.md-5.net/gowonanafi

**Comment by HLX-DENNIS** [comment]
> ### Describe the bug
> https://streamable.com/pfqxvb
> 
> ### How to reproduce
> https://streamable.com/pfqxvb
> 
> ### Screenshots / Videos
> https://streamable.com/pfqxvb
> 
> ### "/ae plinfo" link
> https://paste.md-5.net/gowonanafi
> 
> ### Server Log
> _No response_

I've been experiencing the same bug. On the same plugin version, with the same server version.

Players of my server have reported that they have problems with putting armor on by right-clicking with it.
Normally you can switch between armor and elytra just by right-clicking with it in your hand.

_If i use the previous build: 8.6.12, the bug is gone._

**Comment by Kesims** [comment]
I can confirm this, same issue on my server too.

**Comment by l3unnyAnoF4** [comment]
what should I do?

**Comment by Insprill** [comment]
Fixed in the next update
