### ISSUE TITLE
Heroic armor sucks

### ISSUE THREAD

**Issue by AkaUlti** [GC-spigot/AdvancedEnchantments#2376]
### Describe the bug

heroic armor is weak and you get two tapped

### How to reproduce

use heroic armor

### "/ae plinfo" link

https://paste.md-5.net/ejokidonuv

**Comment by Insprill** [comment]
It shows in the config that the armor attributes only apply to 1.13+

**Comment by AkaUlti** [comment]
then add support for lower versions, that feature was specifically added for cosmic test servers which done run 1.13+, they run 1.8, you made a cosmic test feature that can't be used by cosmic test servers??? why was it dropped for lower versions? it used to work, its not hard to make heroic/leather armor as strong if not stronger than diamond

**Comment by Insprill** [comment]
Not sure when it used to work but in the 8 months I've been working on AE it hasn't been touched other then me making it work on 1.13+ a few weeks ago since it didn't work at all before. Legacy versions don't have any API for item attributes so we'd have to manually apply the NBT data. Considering it took at least 8 months for someone to notice that it just didn't work, it's not the highest of ￼priorities.
