### ISSUE TITLE
Grindstone setting issue

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#2563]
### Describe the bug

There is an option to remove the enchants when people put AE items into a grindstone, though this does not remove the armorset bonus. Causing them to continue enchanting the armorset and kind of bypass the setting.

Is it not possible that we can deny AE items in grindstones, smithing tables and all that kind of stuff?

### How to reproduce

See the above.

### "/ae plinfo" link

https://paste.md-5.net/xayekuhuvi

**Comment by Burchard36** [comment]
Hello there! I know that this issue was opened a while ago, I am a new developer working with GC's team.

I looked into your error and I can confirm that the `events` field for the armor sets are actually indeed still working (As in the armor bonus stays) once ran through a grindstone, I will make sure to look into this and push out a fix for this ASAP

We likely wont disable putting AE items into a grindstone, and rather make the grindstone function so that it removes the armor set bonus when ran through the grindstone

Ill make sure to update you on any fixes we apply for this!

**Comment by Burchard36** [comment]
This bug has been fixed on our end locally, and hopefully will be added to one of the next bug fixes for AE, after I receive some final approvals from GC of course :)

**Comment by Burchard36** [comment]
Hello, this fix was implemented in version 8.9.8 which is out now, have a nice day!
