### ISSUE TITLE
Merged enchants count towards max enchants

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2621]
### Describe the bug

We have max enchants on an item limited to 3. If an item has 2 enchants, one of which has been upgraded to a higher level with a book previously, it is not possible to add a third enchant. The item description only lists 2 enchants, since there are really only 2 enchants on the item, and this behavior is confusing for players.

### How to reproduce

Enchant an item with any 2 enchants, not max level. Use a book, or another item with the same enchant, to upgrade one of the enchants to a higher level in an anvil. Then, use a book or another item to try to apply a 3rd new enchant to the item also in an anvil.

### "/ae plinfo" link

https://opgraphics.co/wp-content/uploads/2021/10/MGUONE2.gif

**Comment by Raxtus14** [comment]
I can confirm this bug further. It's not exactly combining books either... We've encountered this bug with simply certain combinations. We had the case where a netherite pickaxe had Haste III and Soulbound III, but couldn't take Trench IX. We've gotten the books and netherite pickaxe in creative to test if it was truly combining or not. We have no clue what it is, but this bug is not from upgrading the enchantments.

**Comment by bdagenais2** [comment]
Your issue sounds different than the originally posted issue.

**Comment by Raxtus14** [comment]
We did some more in-depth testing. That was one of our suspicions too. We guessed it was because of the books becoming combined for the third enchant exactly like yourself. It is also the same issue of not reaching the maximum number of enchants.

**Comment by GC-spigot** [comment]
Tested combining - can't recreate this. Unless there's a concrete way of recreating this issue not much I can do right now unfortunately, please open another issue with steps on how to reproduce and we'll fix it asap
