### ISSUE TITLE
when I take off the armor, the effects that the armor gave remain

### ISSUE THREAD

**Issue by haroldrc** [GC-spigot/AdvancedEnchantments#2703]
### Describe the bug

when I take off the armor, the effects that the armor gave remain

### How to reproduce

drag armor into inventory without using "shift"

### "/ae plinfo" link

https://paste.md-5.net/goculajeca

**Comment by DuneSciFye** [comment]
Could you get a video of this?

**Comment by haroldrc** [comment]
https://streamable.com/yl4xnx

**Comment by Burchard36** [comment]
Take a look into #2698 I sent a video of over 3 minutes in length equipping, un-equipping re-equipping, you name it 

Not to mention you are running the weirdest fork of paper I have ever seen, as well as that fork having a very dead community and even announcing they won't be supporting any future Minecraft updates (join their discord and click the message link I sent), not to mention this fork has not had any updates in over 2 months, which for a server jar is bad news (What if there was a day 0 exploit, like the Log4J exploit again would they be guaranteed to update they're fork or leave your server vulnerable for x amount of days?), paper, and spigot get updates on the weekly, heck even purpur receives weekly updates, not to mention the official Airplane developer says to use Paper, as he said he will be actively working on Paper on this point forward on top of cancelling all of his supporters patreons

I would strongly recommend changing your software to paper or even purpur, there's no real reason to be using this server software.

Now, I'm not saying this bug is directly related to airplane no, but heaven forbid it IS a bug with that software, we simply won't implement a fix for a rather dead project that even the authors admit they won't update 

Airplane authors discord message: https://discord.com/channels/748023548467216394/753780217117671545/912421001189531758

**Comment by haroldrc** [comment]
I put paper and there is still the problem

**Comment by haroldrc** [comment]
I put paper and there is still the problem

**Comment by haroldrc** [comment]
news?
