### ISSUE TITLE
Explosive Enchant breaks item frames in griefprevention claims (Plugin Incompability)

### ISSUE THREAD

**Issue by marvjosh1** [GC-spigot/AdvancedEnchantments#2743]
### Describe the bug

When shooting a bow with the Explosive enchant in GriefPrevention claims, it will still break item frames even though Explosions are turned off.
When reporting this issue to GriefPrevention, we were redirected to here: https://github.com/TechFortress/GriefPrevention/issues/1771

### How to reproduce

Install bothe AdvancedEnchants and Griefprevention. Created a claim in Griefprevention and disable Explosions in it. Place down some item frames and shoot them with a bow with the Explosive enchants.

### Screenshots / Videos

https://www.youtube.com/watch?v=REvGXXKknKk

### "/ae plinfo" link

https://paste.md-5.net/uhapemidek.css

**Comment by Burchard36** [comment]
Hello, this bug is fixed. This was a pure bug on our end instead of rather the grief protection itself.

The issue was that the plugin was removing the entity(s) if they were not living, this shouldn't of happen it should have only damaged LivingEntities

The code has been fixed and works beautifully on my end :) Expect a fix hopefully in 8.9.1!

**Comment by Burchard36** [comment]
8.9.11 is out now! Please update to the latest version :)

If you have an new issues please open a new issue request!
