### ISSUE TITLE
Neutralize Dupe

### ISSUE THREAD

**Issue by lChrisjm** [GC-spigot/AdvancedEnchantments#2755]
### Describe the bug

If Using a bow with Neutralize, if you hit yourself with an arrow, you get the bow duplicated, so infinitely.

### How to reproduce

1- Got a bow whit neutralize
2- Hit yourself
3- Got another Bow!

### Screenshots / Videos

![imagen](https://user-images.githubusercontent.com/43703371/163861367-a7e6104e-abba-4086-8bee-663c2d8abd07.png)

### "/ae plinfo" link

https://paste.md-5.net/ibiwevekeg

### Server Log

https://mcpaste.io/d9770071e8083279

**Comment by Burchard36** [comment]
https://user-images.githubusercontent.com/48583030/164131069-07cadaa3-2e0a-4f7d-9259-b8d87f0544e6.mp4

Works fine for me! It does disarm yourself, but definatly not duplicate can you give me more information on this? You have a BUNCH of enchantments on that bow, can you try this with only neutralize, then swap out each of those enchantments until a combination of the 2 enchantments cause this bug?

**Comment by Burchard36** [comment]
https://user-images.githubusercontent.com/48583030/164131421-3b4fc575-7db4-4c8f-bc04-4104e2cc353d.mp4

Sorry for the background noice, had family members on the phone

Can you test this with only the disarm enchant? You have a BUNCH of enchantments on that bow and it could be conflicting with 2 enchantments

Also a video would be nice :)

**Comment by lChrisjm** [comment]
Brother, but if you saw the enchantments that the bow had, you could still put the ones it had and try them out, of course, if you were interested in finding a solution.

Anyway, I did it for you, it is the combination of these 3: 

- Abiding
- Neutralize
- Soulbound

https://user-images.githubusercontent.com/43703371/164707432-e94cfcba-9791-4d4d-b7d9-2b1074d4a144.mp4

**Comment by Burchard36** [comment]
This is the info I needed, its a lot better to send a video, as in the video you send the exact way to replicate it (Not to mention you did not mention this was in a WG region, and that it happens when the arrow bounces off another player).

And it's not that "I don't want to fix it" I very much do, I've fixed most issues that rise up within the first few days of the issue being opened, most are before I started working here and I can't exactly get responses from most

And we ask for the specific enchantments and not a list of 15 for these reasons:

1) The ticket mentions "Neutralize" which implies that the only enchant this happens with is neutralize, which is what we test, we only test neutralize or any other enchantments that you specify might cause the bug, we would have expected you to test the bow with only neutralize and verify that the bug works ONLY using neutralize (Which is what we did), this singles out of it being neutralized alone and being a type of enchanting conflict

2) AE is configurable, which means that your enchants are more than likely going to be different from the default enchantments, that's why we ask for the enchantments (IE the configurations) for the enchants

And even with the tested enchantments its still not replicable on my end, are you able to send the enchantments configuration file?

**Comment by lChrisjm** [comment]
It doesn't need to be in a protected region or be hit after a user, it's a way to replicate it, you can hit yourself with an arrow by throwing it in the air and it still works or leave a mob in a protected area to bounce.

I said it was from Neutralize because when I removed the enchantment it stopped working, you know the plugin better than me, that's why you came up with the idea that it could be a combination, the other enchantments were in the image, it didn't cost anything to try.

I have not added new enchantments to AE but deleted a few, I'll pass you the configuration. 

PS: I increased the probability of the Souldboud and neutralize for the tests, after that I commented them to stop working until I found a solution.

Enchantments.yml :
https://mcpaste.io/0f4494c62c12201e

**Comment by vxkShelby** [comment]
Reopening this — I dug into the shipped `9.24.10` jar (decompiled `DisarmEffect.class`, the class backing Neutralize's DISARM action) and the reason it's easy to get "Can't Reproduce" is that the config alone doesn't show the bug — it's in how the effect touches the item.

**Repro (still present in 9.24.10):**
1. Enchant a bow with Neutralize (SHOOT trigger, any level).
2. Shoot yourself with it (self-hit — e.g. point-blank or a ricochet/reflect setup).
3. On proc, you end up with the bow both still equipped/in inventory **and** a second physical copy dropped on the ground.

**Root cause (from decompiling `DisarmEffect`):**
The disarm/neutralize logic touches the same physical `ItemStack` through three independent paths in the same effect call:
- `EntityEquipment#getItemInMainHand()` → cleared via `setItemInMainHand(AIR)`
- A **separate** lookup of the same slot via `PlayerInventory#getHeldItemSlot()` → `getItem()`/`setItem()`
- The originally-captured `ItemStack` reference gets `dropItem()`'d at the victim's location

There's no shared state / no UUID or item-instance tracking tying these three touches together, and critically **no guard for `victim == shooter`** anywhere in the effect or in `enchantments.yml`'s `neutralize` block. When the victim is the shooter, all three code paths execute against what is, from the player's perspective, the *same* item slot at self-inflicted-damage time, and you end up with two physical items where there should be one.

This isn't a config issue — `disable-enchants` (a documented per-world blacklist in `config.yml`) is the only mitigation available to server owners, and that's what we've applied on our end as a stopgap. It fully disables Neutralize rather than fixing the underlying dupe, so players lose the enchant entirely on our server until this is patched upstream.

**Suggested fix direction:** add a `shooter == victim` (or general already-dequipped/already-in-flight) guard before running the disarm logic, and/or track the item by identity (e.g. tag the dropped ItemStack or check `mainHandItem.isSimilar()`+consume the slot exactly once) so the three touch-points can't independently duplicate the same physical stack.

Happy to share the decompiled class snippets if useful — this was reproducible via static analysis, not tested live on a production economy server for obvious reasons.
