### ISSUE TITLE
BlockBreakEvent AutoPickup Error - WorldEdit Error TPS Problem

### ISSUE THREAD

**Issue by Voltikun** [GC-spigot/AdvancedEnchantments#2769]
### Describe the bug

I dont know why but my tps going down a lot and i saw these errors in my console. i hope you can fix this

### How to reproduce

[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/8550090/latest.log)

there is my latest log, mcpaste.io didnt work for me i dont have any idea about this error im using 

Autopickup : 3.9 version  and using latest version of advancedenchants

### Screenshots / Videos

https://prnt.sc/ZD7mEc3jQEVX
https://prnt.sc/3q_dMu_EMCek

### "/ae plinfo" link

https://paste.md-5.net/exesawujax

**Comment by Burchard36** [comment]
Can you send a link to the AutoPickup plugin you are using place

**Comment by Voltikun** [comment]
https://www.spigotmc.org/resources/autopickup.7623/history 

I'm using 3.9 version

**Comment by Burchard36** [comment]
The issue is related to 2 different plugins having the same name

We only have support for AUtoPick with this plugin: https://www.spigotmc.org/resources/autopickup-1-18-support.70157/

But I see you are on a very ancient version of MC, I'm not sure any fix could be implemented other than a config.yml option to toggle at pickup enable

**Comment by Burchard36** [comment]
Closing due to lack of response, if you want to see any feature requests, or your issue is not resolved still please open a new issue referancing this one!
