### ISSUE TITLE
Natural blocks

### ISSUE THREAD

**Issue by Omarlatif** [GC-spigot/AdvancedEnchantments#2795]
### Describe the bug

Feature Request: a condition to check if the block is natural.
https://github.com/GC-spigot/AdvancedEnchantments/issues/2771#issuecomment-1107947633

The plugin already has a safety feature for player placed blocks for more_drops/smelting (one of them)
Perhaps add a condition type for it.

### How to reproduce

-

### "/ae plinfo" link

N/A

**Comment by Burchard36** [comment]
Hello, support for this is rather complicated because the metadata we add to blocks is not persistent through restarts

This is the limitation on Bukkits/Minecrafts end for Block meta-data, only ItemMeta and certain BlockData's (EG Noteblocks) are persistent throughout restarts

Adding this would increase the following issue(s):

1. We would now need to store, each and every single last block placed by a player in some type of storage system, this would result in more RAM usage (As those files need to be loaded in, unless we add in database support eg sqllite) as well as increased performance time as it would have to check the block itself interacted with on top of querying a database if thats how storage is done, 

2. Even if the above is added, this will not work on servers that have been running for a long time, and will only work on blocks recently placed after the said update is implemented

There is no vanilla way to check if a block was naturally placed using any type of Reflection/NMS methods, its another severe limitations on spigot/Minecraft end

I would have to talk to GC about this, as adding this would be a very very large addition (We would basically be remaking Core protects block tracking system)

NOW, we *could* make an option for this suggestion to check against the Core protects database, which of course would require you to have CoreProtect, let me know about this feature as its something that could possibly be added if they're API has methods for checking if a block was player-placed or not of course :)

**Comment by Omarlatif** [comment]
I do have CoreProtect and I'm okay with the resolution.

**Comment by Burchard36** [comment]
> I do have CoreProtect and I'm okay with the resolution.

Sounds good, as we are more inclined to fix all of our bugs first, we will focus on these first before adding support for other things, but this is something that will indeed be added :)
