### ISSUE TITLE
Duplication with Holy white scroll

### ISSUE THREAD

**Issue by DextralityNetwork** [GC-spigot/AdvancedEnchantments#2809]
### Describe the bug

With the holy white scroll at the moment of death and having the item either a helmet or a helmet in your hand, it doubles in your inventory.

### How to reproduce

1) Enchanting a holy white scroll on your armor
2) Fight in pvp with another opponent
3) Before dying have the armor in your inventory by selecting it
4) Die and look at your inventory

### Screenshots / Videos

https://youtu.be/Wp9FsM_lOmU

### "/ae plinfo" link

https://paste.md-5.net/rizupizedu

### Server Log

https://mcpaste.io/6ca11d45878d47ab

**Comment by DextralityNetwork** [comment]
Any Notice the bug persist in the newest version: 8.10.2

**Comment by CYRUS-14** [comment]
Indeed, it dupes. It doesnt go into deathchests on death and drop outside at death location BUT ALSO REMAINS IN INV after death

**Comment by Burchard36** [comment]
Hello there i cannot duplicate this, does the bug still persists after uninstalling the plugin and seeing if it still persists?

**Comment by Burchard36** [comment]
> Indeed, it dupes. It doesnt go into deathchests on death and drop outside at death location BUT ALSO REMAINS IN INV after death

If you need support please open a new ticket, I'm not entirely sure what death chests are and it likely external plugin

**Comment by DextralityNetwork** [comment]
Sorry good, if sel bug is still working with default versions without configuring anything and I tested it on my test server and also created a ticket and I was sent here ....

**Comment by GroundedMC** [comment]
@Burchard36 Hi there - I was about to post the Holy White Scroll duping issue as well but saw this so wanted to share my info here since it seems it may be the same bug.

We have a problem with Holy White Scrolls. We are using deluxe combat to toggle pvp on and off and we have it set up so items drop only during combat, so when players die in combat Holy White Scrolls work just fine, but when they die outside combat they keep all of the items, Holy's are still applied and they get a new pair of items without Holy. So my guess is that Holy White Scrolls cant detect how we set up item dropping in Deluxe Combat, and its giving new items no matter how they die, but Deluxe Combat prevents the original items from dropping so players keep both.
