### ISSUE TITLE
Maxifiers not working.

### ISSUE THREAD

**Issue by ChefJisoo** [GC-spigot/AdvancedEnchantments#2950]
### Describe the bug

None of our maxifiers to improve the success rate of custom enchants are working.

### How to reproduce

Its being drag and dropped with right click, lleft click, shift click and many other ways but it just wont apply. Not basic, rare or advanced.

### Screenshots / Videos

https://youtu.be/_naFnR18MXY

### "/ae plinfo" link

https://paste.md-5.net/fatayehufa

**Comment by Awpmeister2170** [comment]
Hello, What book are you trying to apply this to?

**Comment by ChefJisoo** [comment]
> Hello, What book are you trying to apply this to?

Heya, we are applying it to all the custom enchant books we have and none of them work.

**Comment by Gabris060** [comment]
I am having the same issue even with the latest version. It also spams an error in the console (see separate issue: https://github.com/GC-spigot/AdvancedEnchantments/issues/2946). Could this please be prioritised as soon as possible, because I have seen other people also having this issue where Magic Dust will not apply to increase the book's chance.

**Comment by Awpmeister2170** [comment]
Fixed, please update
