### ISSUE TITLE
The placeholders for orbs are incorrect

### ISSUE THREAD

**Issue by tylerking** [GC-spigot/AdvancedEnchantments#2954]
### Describe the bug

The returned value for %new% & %max% on the weapon/armor/tool orbs are returning the wrong values. They actually seem to be swapped. Could you please fix this. They are pretty much broken because of this.

### How to reproduce

Look at any enchantment orb

### Screenshots / Videos

https://imgur.com/a/h6UAYAL

### "/ae plinfo" link

https://paste.md-5.net/omicilulav

**Comment by reussy** [comment]
Hello @doitliketyler. I don't quite understand, can you explain why the placeholders are incorrect?

**Comment by doitliketyler** [comment]
Well I'm guessing you figured out what I meant since you "mostly" fixed the issue in the update 3 hours after posting this. Thanks for that. There is still one thing thats confusing. It reads as "+-1 Increased slots" when it should just read "+1 increased slots". Why is there a minus sign? It doesn't make sense.

New screenshot:
https://imgur.com/a/DMFtXmc

**Comment by GC-spigot** [comment]
Fixed
