### ISSUE TITLE
KEEP_ON_DEATH for passive death is broken

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2955]
### Describe the bug

If you die via a PASSIVE death but are holding a totem so avoid the death, then any items with the KEEP_ON_DEATH custom enchant will vanish and you'll only get them back next time you actually die

### How to reproduce

Have an item in your inventory with a custom enchant that has KEEP_ON_DEATH. Here is config for mine below for easy copying:

soulmate:
  display: "%group-color%Soulmate"
  description: "A chance to keep item on death."
  applies-to: "Weapons + Tools + Bows"
  type: "DEATH;PASSIVE_DEATH"
  group: "FABLED"
  applies:
    - ALL_SWORD
    - ALL_AXE
    - ALL_PICKAXE
    - ALL_SPADE
    - BOW
    - CROSSBOW
  levels:
    1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"

Now hold a totem and die ONE TIME via a passive method, like blowing up from a creeper. The totem should acitvate and you should avoid death. However, you'll lose the item and will only get it back upon actually dying

### "/ae plinfo" link

https://www.spigotmc.org/resources/80461/

**Comment by Awpmeister2170** [comment]
Hello, Can you provide us with some More info? ie your Server Version and Plugin Version ( Your /ae plinfo is incorrect as it link to a different resource?

**Comment by BrandonT80** [comment]
I can confirm this happens and have found a fix to it. The fix however should really be hard programmed in to avoid this though. 

The temporary fix is to check if the victim is holding a totem of undying, and if so, stop.

Example:
condition:
        - "%attacker mob type% = PLAYER : %stop%"
        - "%victim is holding% = TOTEM_OF_UNDYING : %stop%"
        - "%victim offhand item% = TOTEM_OF_UNDYING : %stop%"
      effects:
        - "KEEP_ON_DEATH"
        
@Awpmeister2170 
To explain better, soulbound causes the item to not work properly if a totem is used. The item deletes itself essentially. I assume theres some code behind the scenes that deletes the item rather than drop it on the ground and since the player did not fully respawn, the item is gone. This helps mitigate that issue. Some members did report actually dying would give them the item, but a logout broke this chain.

**Comment by GC-spigot** [comment]
Fixed
