### ISSUE TITLE
Dupe Bug (URGENT)

### ISSUE THREAD

**Issue by ItsNoWorry** [GC-spigot/AdvancedEnchantments#3081]
### Describe the bug

If you hold the right click when applying gear it dupes it. 

### How to reproduce

Just hold right-click on a full set of gear and something will dupe. Different pieces every time. 

### Screenshots / Videos

https://gyazo.com/4925f8090e410caeec7c561ce19de12d

### "/ae plinfo" link

https://paste.md-5.net/agitexixir

**Comment by GC-spigot** [comment]
Have you disabled armor switching in your factions config? This is always the case with such issue.

**Comment by ItsNoWorry** [comment]
> Have you disabled armor switching in your factions config? This is always the case with such issue.

I figured that was the issue but I also want that feature enabled. Is this bug going to be fixed by the next update?

**Comment by GC-spigot** [comment]
This isn’t a bug. Disable it in factions plugin - advancedenchantments has it by default, so they are just conflicting On 2022-11-01, at 01:42 AM, ItsNoWorry ***@***.***> wrote:﻿

Have you disabled armor switching in your factions config? This is always the case with such issue.

I figured that was the issue but I also want that feature enabled. Is this bug going to be fixed by the next update?

**Comment by ItsNoWorry** [comment]
![image](https://user-images.githubusercontent.com/65502929/199131295-f02fbf3c-03d8-4ca4-bbce-7bfd58d838eb.png)

Ahhhhh look at this haha. You're right, thanks for the help!
