### ISSUE TITLE
Telepathy doesn’t count towards player stats

### ISSUE THREAD

**Issue by redpid42** [GC-spigot/AdvancedEnchantments#3135]
### Describe the bug

When I use tools with telepathy (for example: pickaxes) it wont count the blocks i mine towards player stats. This can also mess up plugins like BeautyQuests with quests to mine blocks it doesn’t count blocks broken with pickaxe with Telepathy

### How to reproduce

1. Open statistics and search how much of a certain block (for example: Stone) you mined
2. Get a pickaxe with telepathy
3. Mine the block that you looked for in the stats
4. Open stats again
5. It shouldn’t change the amount broken, even though you broken the blocks normally

### "/ae plinfo" link

https://paste.md-5.net/mehibucoka

**Comment by reussy** [comment]
Hello, this problem has been fixed in the version **[8.15.8](https://www.spigotmc.org/resources/1-8-1-19-3-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-25-sale.43058/update?update=474713)**

Please upgrade to this version from Spigot or use the latest version in beta mode.
@Awpmeister2170

**Comment by Awpmeister2170** [comment]
Closed due to already being fixed. ( please update as stated above )
