### ISSUE TITLE
Custom enchants work when if off hand

### ISSUE THREAD

**Issue by SnowkyY** [GC-spigot/AdvancedEnchantments#3218]
### Describe the bug

Hi, custom enchants work while in off hand. This is really annoying and I have found no way to fix. Could I please get some help.

### How to reproduce

Place a pickaxe with haste 3 in ur off hand

### Screenshots / Videos

/

### "/ae plinfo" link

/ae plinfo skipPlugins

**Comment by cynikhavoc** [comment]
Yes, also if  you equip gears 3, or overload 3 and un-equip the effect stays

**Comment by Dakotaa** [comment]
While this is probably intended and not a bug, it is annoying since it allows enchants to be used in unintended ways. For example, a pickaxe that grants Haste II can be held in the offhand while using a sword in the main hand to get faster swing cooldowns.

A config option to disable effects from working while in the off-hand would be nice.

**Comment by GC-spigot** [comment]
Working on this!

**Comment by aaa8881** [comment]
> Working on this!

so is it intended that custom enchantments applied in offhand tool are also activated when action is triggered by mainhand?
