### ISSUE TITLE
Feature request - Enchantments folder

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3473]
### Describe the bug

So, make current enchantments.yml as folder, where you can make as many .yml files as you like but plugin will read them all. So you have option to organize your enchantment by category and/or usage. Same system like AdvancedItems has now, this could make alot sense. Like having different types of enchantments in one folder, pvp ones in other, mining ones in other etc. 

### How to reproduce

Same as above :)

### "/ae plinfo" link

no link

**Comment by z1haze** [comment]
+1

**Comment by GC-spigot** [comment]
We've debated this internally many times. While this does make sense for AdvancedItems, as item files are huge, enchantments tend to have smaller configuration sections, therefore it's not as messy. 

I'll look into how user-friendly would the transition be, possibly add support for both methods long term so a lot of premade configurations which are already available don't become obsolete.

**Comment by z1haze** [comment]
you could make it backwards compatible by still loading an enchantments.yml file if it exists, otherwise look at the files in the enchantments folder.

Lots of us are very meticulous when it comes to organizing and be able to categorize enchantments by different files would allow multiple teammembers to take on different tasks of handling different types of enchantments, like weapons, tools, armor, or even more specific boots, chestplates, etc.

My usecase is I have cherry-picked individual enchantments, have a nice clean file, alphabetized them.. and when i went to install the pvp pack because i wanted some from there too, and it deleted all of my enchantments.. it should be easy to just run this and create 2 separate files and have them both be imported.

**Comment by ELIAS7281** [comment]
i second this, having enchantment groups in folder categories would be cool.
