### ISSUE TITLE
Bugged to activate the EFFECT_STATIC in 1.17

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3557]
### Describe the bug

The bugged occured when you guys tried to update the visual update to potion effect.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/a0cbf36e-3e09-4a6e-a634-4c2f1b48e788)

Suggestion to have an option to have an On and Off for the visual update.

or if can't, is it possible to just revert the old update?

### How to reproduce

Just go to a 1.17.1 server and have a 9.3.7 or the latest update of ae and you'll be able to replicate it. 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/23b41dcb-9b09-4e29-aa83-f4032bf63af5

### "/ae plinfo" link

https://paste.md-5.net/xekamajute

**Comment by DingoBruh** [comment]
Hey, I also have that same bug and it only started happening to me since I upgraded the plugin to the latest version. My server supports versions from 1.14 - 1.20.X using **ViaVersion/ViaBackwards**. There is **no error** in the **console** about this and the effects don't stay longer than **1sec**. Please fix it soon : /.

**Comment by ttt0** [comment]
I also have that same bug

**Comment by FaiqGaming** [comment]
I also got the same bug issue in AdvancedEnchantment plugin version 9.3.7 on my mc server Pufferfish 1.18.2

**Comment by GC-spigot** [comment]
Fixed next update!
