### ISSUE TITLE
Soulbound Dupe Bug

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#3651]
### Describe the bug

Bug still happening i've reported in #3520

### How to reproduce

Just die with soul bound items in keep inv enabled world... Or 

### Screenshots / Videos

https://gyazo.com/9a2796bb4cf724e3b79efe15998bd338

### "/ae plinfo" link

https://paste.md-5.net/qifusoyahi

**Comment by Rexmen1** [comment]
And we just tested happens even without keep inv is enabled or not...

**Comment by ThomasWega** [comment]
Then you most likely have a plugin conflict, as it still works just fine for me. No dupe at all...
https://i.imgur.com/jHZ1qpK.mp4

You can try on a completely fresh server with the latest AE version and let me know

**Comment by Rexmen1** [comment]
How's it other plugins problem if something is caused by advancedenchantments? Well I guess As long something works fine in your end is enough... TY

**Comment by ThomasWega** [comment]
I've suggested you try with the latest AE version and only AE on the server, to see if the issue is still present. No idea why you have the need to go and post a one star review, when I am handling your issue right now. If it is a plugin conflict, we try to fix those as well, but first need to identify them
