### ISSUE TITLE
Enchantments being removed

### ISSUE THREAD

**Issue by Real6dq** [GC-spigot/AdvancedEnchantments#3693]
### Describe the bug

When a user applies an enchantment to an item that already has a few enchantments, the other enchantments would be removed for some reason. Using 9.4.4 which is 2 versions behind, but 9.4.5 and 9.4.6 are just updates for 1.20.2 and fixes for them.

### How to reproduce

Apply X enchantments till max enchantments, then apply any enchantment, then the bug would happen, previous enchantments removed, new enchantment added.

### Screenshots / Videos

https://prnt.sc/Lz5uCSG97Ras
https://prnt.sc/68xQKyYhhsz1
https://youtu.be/eD7Gr70VQyI

### "/ae plinfo" link

https://paste.md-5.net/emofuzodop

**Comment by aXe18** [comment]
Same happening for me

**Comment by GC-spigot** [comment]
> Please fix this asap, it's annoying and frustrating, or just open source the code and I'll fix it for you.

This isn’t an issue with AE, already looked into it. Try with a default configuration and no other plugins and you’ll see.

**Comment by GC-spigot** [comment]
@Real6dq It's not NBT issue. You can see in the lore that NBT updates and increases. 
From what @aXe18 showed me, it seems like it's the same issue. Feel free to send your AE configuration and we'll take a look with your config, but with aXe's config we couldn't recreate this issue.

**Comment by aXe18** [comment]
Yes, i can confirm this, i commented issue since it was happening also to me.
But enchant itself dont disappear anywhere, its only lore and i will tell resolution here or somewhere if/when i find it, but with configs only and not any other than essentials, amobs, apets, battlepass, IA, actually just all AP plugins since its my test server, there that does not happen to me. 
Coomon plugins we have on /ae plinfo is (Aureliumskills, Citizens, DH, fawe, essentials, gsit, multiverse, PW, protocolib, skinrestorer, tab, vault and worldguard) And if i have to take quess what is causing issues, it is most likely Aureliumskills xD

**Comment by GC-spigot** [comment]
> Could you also add something like an /enchantinfo? That'd like show to what items the enchantment book can be applied and so on?

Like what we have right now with `/ae info <enchant>` or `/enchant <enchant>`?

> Sounds good, any ETA when this will be fixed? My players are waiting.
We can't fix what's not caused by our plugin :/

**Comment by aXe18** [comment]
@Real6dq Can you pls go all "not so common" plugins trough one by one and see what plugin causes the issue ? 
In my case, it was caused by wolfyutils
