### ISSUE TITLE
Urge for better testing environment to improve stability of plugin. 

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3770]
### Describe the bug

This is not a bug. 

I've used AE in my old previous server few years ago, and has been using it for current server for an year. 
I saw AE has survived for years, generated couple hundred thousands of revenues by selling many copies. 

As a plugin(or program) that multiple servers may use, I believe plugin should acquire better stability - and this can not be done by simply trying harder in current way. human fails, but automatic test does not. 

We all make mistakes. I make numerous amount of mistakes from coding. As you may already know, simple arithmetic mistake can result into big consequences especially when we're talking about chances. It's giant problem if enchantment book with 1% chance is applied in 100% chance. 

Based on my observation and experience of using AE for years, I have to doubt there is unit test to check these things out. AE has been sold multiple copies but all minecraft plugins are not comparable to giant open source projects. we can't achieve 100% coverage for every single functionalities, but we can do for some of them - especially critical ones and for functionalities that exists and will not be changed. 

I hope you don't consider CMI as your competitor plugin as they're targeting for something quite different. I'm unsure why CMI is being attacked by others sometimes, but I trust CMI in general. From CMI 5 to 9, I generally never experienced something so randomly broken in all minor updates. may things change from major version changes, yes. I think it's more to plugin user's responsibility to look at changes and adjust accordingly for major updates. However, plugin user may assume all functionalities may work as expected. I did, and CMI did fulfill my expectation. 

AE fails to do so, in my experience so far. 

Almost every time I update from different minor version, there was problems. Trench and Veinminer caused duplication bugs, some mechanics crashed server or consumed lots of tickes from overflow, items randomly stopped working , or doesn't work as expected as so on. Unfortunately, I didn't write all list down to complain, so can't think of exact cases, but you will know better than me about problems.

You may argue AE is different from CMI. Of course it is. I code for living, and made quite a few different minecraft plugins for my private servers. There definitely are much more chance for AE to generate bugs than CMI. The point is approach. All major programs have test. The fact that there are minor all sort of different programs in all minor versions indicates failure in automatic testing. 

You may or may not have read my raged ticket in discord. tracking down player's usage of enchantments and trying to rollback economical damage for hundreds of books used is not fun. This is avoidable problem and I believe it must be avoided. 

I suggest you to seriously think of this suggestion and improve some things so that plugin becomes truly mature.
Also, I suggest you to seriously rethink of spigot 9.5.4 changelog and judge if that's proper thing to add in "official" changelog. 

### How to reproduce

-

### "/ae plinfo" link

-

**Comment by GC-spigot** [comment]
Comparing to CMI is not fair for sure, it’s general tasks are much less complicated. Our effects juggle between hundred of them being all compatible, each and every of mining effects activating with correct timing, handling custom block breaks with NMS to not have a performance impact, as well as:
- silk touch
- fortune
- generating drops since vanilla ones arent reliable
- handling multipliers correctly for each drop otherwise we can dupe items that shouldnt multiply
- handling all broken containers correctly
- smelting drops if needed
- breaking surrounding blocks
- handling protection for all of those custom broken blocks
- dealing with all the platform inconsistencies and issues that appear in one build, disappear in the other

While doing all of this, dealing with other plugin block breaks. Every step of the way aureliumskills’ implementation proved problems, from their canceling of events completely not working, us having to create a multi-threaded system to handle their extra drops because we cant prevent them from not dropping their custom drops (again cancel not working), to even lore lines disappearing because of it.

We contacted and got nothing back from them. I agree that we should work on the inconsistency between updates, and Ive been working on automating tests before updates (should be quite doable with the mining effects), not everything can be tested, and with so many combinations even changing anything not related sometimes affects the system behind effects. 

Your calculation of how much “we made” is wrong as well, that’s an insane number. Plugin price when launched was 4 EUR for a while, and until a year ago it was less than 10 Eur. We pay our developers and support staff. 

I agree that there is a problem with updates testing and can promise you we will do better.
