### ISSUE TITLE
Reforged enchantment doesn't work

### ISSUE THREAD

**Issue by daniel-skopek** [GC-spigot/AdvancedEnchantments#3781]
### Describe the bug

Reformed enchantment doesn't work

### How to reproduce

1. Break block with tools that has Reforged enchantment
2. The tool will damage normal (fast) as without the enchantment

### "/ae plinfo" link

https://paste.md-5.net/lubiyuhuri

**Comment by ThomasWega** [comment]
The enchantment does work, however we've had the values in negative even though they should be in positives. So it was actually taking 2 durability points rn even though it should've taken 0. Fixed in. You either need to recreate your config after updating or change the values to positive numbers yourself
