### ISSUE TITLE
Crash when using trench enchant and shovel skill from auraskills

### ISSUE THREAD

**Issue by matipoirierg** [GC-spigot/AdvancedEnchantments#4166]
### Describe the bug

If you activate the shovel skill from auraskill and the shovel has the trench enchant the server will explode.

### How to reproduce

If you activate the shovel skill from auraskill and the shovel has the trench enchant the server will explode.

### "/ae plinfo" link

https://paste.md-5.net/ehikedilid

### Server Log

https://mclo.gs/M8ccfZF

**Comment by Nanpure** [comment]
I have this issue as well. It did not occur in Aurelium Skills 1.3.24. I'm not certain if this can be fixed in AE or if it must be fixed in Aura Skills. Try commenting on my bug report there to boost visibility:

https://github.com/Archy-X/AuraSkills/issues/250

Disabling the enchantment for shovels in AE will not prevent the effect from triggering on already enchanted shovels. It must be disabled conditionally. I would like to have done this via regex, but this feature appears to be broken:

https://github.com/GC-spigot/AdvancedEnchantments/issues/4125

**Comment by GC-spigot** [comment]
I've left my comment there as well, it's 100% them.
