### ISSUE TITLE
Starting from version 9.7.9, this error occurs. Korean input prohibited in Enchantments.yml

### ISSUE THREAD

**Issue by madebygood** [GC-spigot/AdvancedEnchantments#4176]
### Describe the bug

Starting from version 9.7.9, this error occurs. Korean input prohibited in Enchantments.yml

### How to reproduce

헤르메스:
  display: '%group-color%헤르메스'
  description: '&f착용중 신속함이 부여됩니다.'
  applies-to: 부츠
  type: EFFECT_STATIC
  group: ELITE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:0
오버로드:
  display: '%group-color%오버로드'
  description: '&f착용중 생명력 강화가 부여됩니다.'
  applies-to: 모든 부위 갑옷
  type: EFFECT_STATIC
  group: ELITE
  applies:
  - ALL_ARMOR
  levels:
    '1':
      effects:
      - POTION:HEALTH_BOOST:0
    '2':
      effects:
      - POTION:HEALTH_BOOST:1
    '3':
      effects:
      - POTION:HEALTH_BOOST:2
    '4':
      effects:
      - POTION:HEALTH_BOOST:3

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/43653581/ad281ab4-1925-4be7-b961-6f6b97abbf15)

### "/ae plinfo" link

https://paste.md-5.net/ecihumogak

**Comment by GC-spigot** [comment]
Hi! Yes unfortunately new system uses Spigot's PersistentDataStorage and it does not support characters other than Latin :( We cannot do anything about this, since the system we used before (NBT) is removed by Mojang for 1.20.5 update. 
https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out
