### ISSUE TITLE
API method to ignore drops with NBT

### ISSUE THREAD

**Issue by Projecki** [GC-spigot/AdvancedEnchantments#4378]
### Describe the bug

When using a chunk collector from https://www.spigotmc.org/resources/zithiumcollectors-1-20-chunk-collectors-crop-mob-hoppers-optimized.114135/ as well as Telepathy enchant, crops that are broken are sent both to the collector as well as put into your inventory. This creates double the crop yield as expected.

### How to reproduce

Break any block or crop using telepathy enchant in a chunk with a chunk collector 

### Screenshots / Videos

https://youtu.be/EwHaEYUByGQ

### "/ae plinfo" link

https://paste.md-5.net/nogolonare

**Comment by Projecki** [comment]
ZithiumCollectors dev ask I make a report here

**Comment by ThomasWega** [comment]
The dev should modify the drops of the items on lower

**Comment by Teamplayer** [comment]
@ThomasWega Feel free to elaborate on how to do that. I'm not sure how active you are in the development of AE, but AE doesn't care about previous events and generates telepathy items based off of `Block#getDrops` which as you may know returns a copy of a list of what that kind of items that block can drop. Are you suggesting other plugin authors use reflection to modify what that method returns before and after it is read by AE just to supply AE with the correct data?

**Comment by ThomasWega** [comment]
I didn't realize it was a copy and that it's immutable. Although it does seem pretty unrealistic to add hook to every plugin which has similar interaction to yours. Worst case scenario I just add hook to your plugin or check for nbt on items. I wonder if you have any other ideas how to approach this?

**Comment by Teamplayer** [comment]
@ThomasWega I'm not the developer of the ZithiumCollectors, just a helping for fun. Both plugins need to update to using `BlockDropItemEvent` instead of listening and modifying the drops on the `BlockBreakEvent`. This list at `BlockDropItemEvent#getItems` **does** have the desired functionality. This list can be modified and subsequent listeners will get  the same list to modify as they see fit. I understand this isn't that small of a change, but it will increase compatibility in both plugins with other plugins. @ItzSave Tagging you so you can implement the change in ZithiumCollectors as well.

**Comment by ThomasWega** [comment]
This unfortunately most likely won't be applicable to us. The ways our abilities work, I don't think we can listen to this event while keeping the same functionality as intended. I am able to ignore items with certain NBT in drops though

**Comment by Teamplayer** [comment]
What were you thinking for that? Does AE have a public API that other plugins can hook into? If so, the best option would be to provide a utility method somewhere to add the right NBT to an item stack so that AE can tell what to ignore. I do think implementing the other event would be the best for long term compatibility, but I understand that is an undertaking considering the structure of the project.

**Comment by ThomasWega** [comment]
Creating a method in API that will keep list of string NBT to ignore could be the solution. And pretty easy to implement for everyone imo. What do you think?

**Comment by ThomasWega** [comment]
Has been added.

**Comment by ThomasWega** [comment]
Added. Next update
