### ISSUE TITLE
Reforged and Abiding durability decreases faster

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4420]
### Describe the bug

When enchanting a custom item from ItemsAdder with Reforged or Abiding the tool somehow breaks faster.

### How to reproduce

Using both /ae enchant or drag n drop on a custom item from ItemsAdder with Reforged or abiding.

### Screenshots / Videos

https://youtu.be/LTtFFCa-jJs

### "/ae plinfo" link

https://paste.md-5.net/ecusuzonod

### Server Log

No errors on console.

**Comment by ThomasWega** [comment]
Also had report about this happening with regular items, not only IA. Will investigate

**Comment by slyleight** [comment]
ThomasWega I can confirm that this issue is occurring, although I didn't report it initially. My apologies for that oversight.

For some reason, any effect that modifies the durability of an item added with ItemsAdder does not work as intended. When I tested it, I realized the effect always affects the item's durability negatively. For example:

- ADD_DURABILITY_CURRENT_ITEM:+2 / -2 / 2 => Always removes 2 durability, just like (-2).
- ADD_DURABILITY_ARMOR:+3 / -3 / 3 => Always removes 3 durability, just like (-3).

I think it is because we can define a custom durability for that item with ItemsAdder. On our server, we have custom textured items that are leather but have stats similar to netherite armor.
