### ISSUE TITLE
problems with worldguard

### ISSUE THREAD

**Issue by Z3r0xh** [GC-spigot/AdvancedEnchantments#4425]
### Describe the bug

The problem is when you deny with conditions that an enchantment does not work in a Wolrdguard region in the following way.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/0810686e-6240-4b6b-9a1d-fc88166bae72)

When you are, for example, in the region in this case "parkour" and you equip armor with an enchantment that is denied in this area, it will not apply, since it is denied.

But, if you come from outside the region with the armor equipped, the enchantment still works:

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/d5402445-4eb5-4257-9dc2-e3344b8ea48e)

There is also the problem that if you come from outside the region with an enchantment and enter a region with the enchantment that is denied, you can remove your armor and the effect persists on you, making you able to stack different attributes.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/138524212/3a42f219-3919-4d6c-a28a-677cada2dbd8)

As you can see I don't have the votes but the jump effect continues

### How to reproduce

In this case it only creates a region called parkour and denies an enchantment in it.

Check that if you are inside and equip the armor, it will have no effects.

Now leave the region and equip yourself and re-enter it and you will see that the enchantment and its effects persist.

### "/ae plinfo" link

https://paste.md-5.net/recisuqera

### Server Log

https://mcpaste.io/c7a2c5def8d10d51

**Comment by GC-spigot** [comment]
Problem with this is, which is also unfixable and unavoidable:
EFFECT_STATIC only activates 2 times - when armor is added and removed. Hence the permanent potion effect given. 

It cannot be solved, this is done for performance reasons. If it was different (that is - continuously checking land, armor etc) there would be major lag. 

We'd recommend switching this to a REPEATING type if you want to disable it in an area, otherwise not much more can be done.
