### ISSUE TITLE
Usage for API

### ISSUE THREAD

**Issue by Lia-LV** [GC-spigot/AdvancedEnchantments#4442]
### Describe the bug

Not bug, but I want to know how can I use API on 9.9.11 version,

Added API method and config list to ignore drops with certain NBT
Added setIgnoreBlockEvent method to AEAPI

How can I use these?

sorry for write this on bug report, but discord's helper(moderator) said they can't help about API, so I must go to github.

### How to reproduce

not related

### "/ae plinfo" link

not related

**Comment by ThomasWega** [comment]
Hey! It will be changed a bit on the next version, because it did not work properly. The wiki in few hours, but here's the link now
https://ae.advancedplugins.net/for-developers/plugin-compatiblity-issues#tp_drops-duplicating-drops-to-multiple-inventories

Wait for the next update, then you can code it. Apologies for the inconvenience and change of code
