### ISSUE TITLE
Blockbreakevent

### ISSUE THREAD

**Issue by Batman5664** [GC-spigot/AdvancedEnchantments#4492]
### Describe the bug

it accures with almost all pickaxe enchants. veinminer , trench, smelting,telepathy. you just get errors of block break event(see picture)
![error](https://github.com/user-attachments/assets/55df482e-746b-4cf8-8ed7-cc49cc9a4feb)

### How to reproduce

use version 9.9.17 and put any of named enchants on your pickaxe , veine miner, trench , smelting . and try to mine ores or relevant blocks.

### "/ae plinfo" link

https://paste.md-5.net/oyobazivuz

### Server Log

see picture uploaded in discription

**Comment by svyoshi** [comment]
Can confirm, experiencing this as well.

**Comment by slyleight** [comment]
Can confirm, I had to revert the plugin back to 9.9.14. A lot of stuff gets broken with each update. 
_(A lot of stuff is still bugged in 9.9.14 too. I may revert it back to 9.8.9 as well. I can't understand what is working or not; patch notes are not reliable anymore.)_

- REPEATING still doesn't work. (Who approved that it was working?)
- Block Updates don't work.
- HELD enchants are still getting bugged (infinite working) after a world change.
- The document is missing a lot of information.

I miss the old patches where things used to work.

**Comment by GC-spigot** [comment]
Sorry about the problems! We are now almost done implementing automated testing between updates, it's now working just perfecting it. 

To address problems, that's so weird, we cannot replicate some but most are due to 1.20.5 onwards changes, where a lot of events are not called internally from spigot/paper, methods not working etc. It feels experimental still but that causes us to have troubles trying to make it work for everyone, I'll look into these problems today.

**Comment by GC-spigot** [comment]
This issue is now solved,
