### ISSUE TITLE
Holywhitescroll Keep-On-Death issue and another issue

### ISSUE THREAD

**Issue by PengBread** [GC-spigot/AdvancedEnchantments#452]
**ISSUE#1**
Holywhitescroll keep-after-death: true option is still not working. I have set this to true and the items still drop on the floor when I die. Only when set to false it works. 

In my previous thread you mentioned its fixed, I'm not sure you meant as in fixed for a later on update or 5.6.0 etc. If you meant by 5.6.0 fixed, no its not. Still having the same issue.

By the way, I'm using default config to test out this issue. So its not config issue.

**ISSUE#2**
Holywhitescroll lore added to Mythicmobs items or any item generators through their config won't work for them. For example, you added "> Soulbound <" lore to the item, but the holywhitescroll effect doesn't work. Only the ones added with gems directly in-game works.

No errors.

**Comment by GC-spigot** [comment]
Fixed First issue, but second issue isn't fixable. Basically, my plugin uses NBT rather than Lores for recognition so user experience doesn't have to be limited with-in my plugin (aka you can have an empty lore line set in config and it will still work), but this causes an issue like that where just simply adding text to lore from other plugins won't work.
