### ISSUE TITLE
Undamageable target not working

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4522]
### Describe the bug

This type of targeting is not working in any circunstances, I tested with faction allies, godmode, creative and others. Same problem as #4342. I tried to use this way:
```yml
      effects:
        - 'POTION:REGENERATION:3:80 @Aoe{radius=16,target=undamageable}'
        - 'POTION:DAMAGE_RESISTANCE:0:80 @Aoe{radius=16,target=undamageable}'
```

If I change `undamageable` to `all` will work.

### How to reproduce

Try to use `@Aoe{radius=16,target=undamageable}` target with someone, it doesn't work.

### "/ae plinfo" link

https://paste.md-5.net/jeruwahajo

**Comment by ThomasWega** [comment]
Aoe seems to work as usual. Now, it's true that it did not work with gamemode creative, because it technically doesn't cancel the damage event. That will be fixed in the next update. Works fine with essentials god mode. If it doesn't work with any other plugin, it's probably because it doesn't cancel damage event. In that case, there's not much we can do, and the other plugin needs to improve their logic
