### ISSUE TITLE
Perfomance issues with onMobDeath and onEntityDeath

### ISSUE THREAD

**Issue by ArefyNetwork** [GC-spigot/AdvancedEnchantments#4602]
### Describe the bug

Perfomance issues when too many entities are killed

Github in WildStack's github: https://github.com/BG-Software-LLC/WildStacker/issues/887

Spark: https://spark.lucko.me/OMFKZg4JJk

I thought it was caused but WildStacker, but as WildStacker handles mob kills, if you open all you'll be seeing advancedenchantments plugin.

Thanks!

### How to reproduce

Many players farming mobs with their swords in a mob farming gamemode, (like skyblock for example):

(The lag seems to be caused by net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(), net.advancedplugins.ae.items.AEItem.onEntityDeath())

### "/ae plinfo" link

https://paste.md-5.net/inujeniyas

**Comment by GC-spigot** [comment]
My guess is that you allow them to "one hit" mobs and they are spamming mobs at insane values. The load coming from this is caused by hitting the limits of server software rather. Here as you can see:
![image](https://github.com/user-attachments/assets/76eed384-eeee-49f2-a588-fa6615b40f60)
It takes a lot of time to just read data from an item, which is done by Spigot/Bukkit by reading world data. 

I did now update the code a little bit, at best there will be maginal gains as all the other lag is caused downstream. I only could recommend preventing the spam-killing mobs or letting them kill more than just 1 at a time - e.g. whole stack.
