### ISSUE TITLE
Silktouch + veinminer doesn't work correctly

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4678]
### Describe the bug

Silktouch + veinmine should only give silked touched items in their pure form but they give ingot form...

### How to reproduce

Just have silk touch + vein miner and test?

https://github.com/user-attachments/assets/fb2f9f2b-abfc-4c47-a828-9c977baaa69c

### "/ae plinfo" link

https://paste.md-5.net/eceweledas

### Confirmation

I Confirm

**Comment by GC-spigot** [comment]
Glowstone does not work with Veinminer, that is broken by `Super Breaker` from McMMO as you can see in your action bar: 
![image](https://github.com/user-attachments/assets/33cb0209-a765-4a42-9325-e64ab2491b38)

Veinminer whitelist: 
![image](https://github.com/user-attachments/assets/95464cdf-3e57-4706-9aba-30a062ff2c40)
Glowstone 

And the enchantment does correctly work when glowstone is added: https://gyazo.com/c469018c4c8ab9ccd33f3bb2e2ed4c4a

I have no clue why McMMO ignores Silk touch, but my guess is that is how their `Super Breaker` ability is supposed to work.

**Comment by GC-spigot** [comment]
And update: veinminer does work correctly on other ores as well: https://gyazo.com/39402a1103619b66d2850397e3c6ba09
This is mcmmo.

**Comment by leon37921** [comment]
Its another thing with the mcmmo hook.
It also affects the Telepathy-Enchantment
and also affects normal cleanstone and all ores.

You get one "silktouch" item (glowstone) and one "normal" item (glowstone-dust) instead of two silktouch items with mcmmo bonus-drop.
Mining level 1000.
latest mcmmo, AE 9.15.2
can't upload a video, because github said it failed
