### ISSUE TITLE
AE Version 9.12.3+ breaks compatibility of mmoitems custom nbt tags

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4688]
### Describe the bug

So when I updated AE to 9.12.3, I can't see AE enchants on mmoitems using custom-nbt and they are not even applied. 
Example MI item:

```
custom-nbt:
    - ae_enchantment;soulbound 1
```
Items with this nbt got this enchant previously in 9.12.2, thanks to my custom plugin it's even visible in lore, howewer right now it has no effect at all, enchant is not applied, not in the lore too. It's written in nbt tags when I run /paper dumpitem, so don't know where the problem is.

Tags i've found
`MMOITEMS_CUSTOM_NBT:'["ae_enchantment;soulbound 1","EXTMI_ae_enchantment;soulbound 1"]'` & `"ae_enchantment;soulbound":1`

Older functional items had this
`PublicBukkitValues:{"advancedenchantments:ae_enchantment-soulbound":1` which fresh new given items lacks

So AE for some reaons broke this compatibility somehow.

### How to reproduce

Give a new item with ae enchant on it.

### "/ae plinfo" link

https://paste.md-5.net/utoluwimuk

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Are you sure this was caused by AE update and not MMOItems update?

**Comment by TheLaoming** [comment]
100% sure, because I did not update MI since then. I use same dev build like on production server.

**Comment by kevinwang-0916** [comment]
I got this issus also.

**Comment by GC-spigot** [comment]
We've now fully moved away from NBT to PDC. The developer of MMOItems needs to update their code to use our API to apply enchants.

**Comment by kevinwang-0916** [comment]
But I did not install MMOItems and still have this problem.

**Comment by TheLaoming** [comment]
Well, I don't think it's related to PDC because you already moved away months ago and this specific problem, is broken since this AE (not MI) build. And I do use one of the most recent builds of MI which I believe it works fine and was fine and let's say compatible in this way w AE all the time, however PDC is still NBT. You just probably changed some kind of tags recently.

**Comment by GC-spigot** [comment]
We completely removed any NBT support last month, that is why this is only happening now. We had a backup system which would parse old NBT items, but since this is now removed, any system which relied on NBT system no longer works. 

This was a grace period of 5 months since moving from PDC, it should have been enough to move away for everyone from it. 
"PDC is still NBT" it is treated differently, PDC is now in `custom` data. 

If enchantments were applied via API this would work correctly. `MMOITEMS_CUSTOM_NBT:'["ae_enchantment;soulbound 1","EXTMI_ae_enchantment;soulbound 1"]' & "ae_enchantment;soulbound":1` data would work with old system but we completely gotten rid of any NBT systems we had before and solely rely now on PDC systems by Spigot. 

This is not an AdvancedEnchantments issue and rather an issue with integration

**Comment by kevinwang-0916** [comment]
Then what can I do to make my old items work?

**Comment by GC-spigot** [comment]
We literally moved from NBT-api in April and have not applied anything using NBT api since, all items since then were automatically being migrated. There is nothing we can do as there was a 5+ month grace period.
