### ISSUE TITLE
Enchants that are not working

### ISSUE THREAD

**Issue by report101** [GC-spigot/AdvancedEnchantments#501]
spigot ver >> 1.8.8
plugin ver >> 5.6.6
------------------
BLESSED-enchant
------------------
so i figured out whats wrong if the de buff is >>infinite<< the bless will not work
if the de buff has a >>time limit<< only will the bless enchant cure it 
------------------
SHACKLE-enchant
------------------
mobs still take knock back tried for a few hours also pls make SHACKLE 3 do completely no knock back
-------------------
IMPLANTS-enchant
-------------------
not working for me at all even with alien implants
how did i test  it ? ez apply enchant to helmet and just ran straight hunger bar did not go up at all

**Comment by GC-spigot** [comment]
1st - supposed to function like that. It doesn't remove permanent potion effects, only timed ones. If you want it to remove permanent replace CURE: with CURE_PERMANENT:
2nd - fixed
3rd - set the time to 1 and add a message to the effects list - you will notice that the enchant works just very rare due to it having low chance & cooldown after it runs.
