### ISSUE TITLE
Literal copy of my review in the proper place so you'll consider it.

### ISSUE THREAD

**Issue by CaptainAmpersand** [GC-spigot/AdvancedEnchantments#621]
One thing I disagree with, relating to your response to KokoBerry, is the fact that Trench is truly... Needing another rework. Her issue wasn't with a blacklist, it was the choice of tool.

For example, if a player is using a pickaxe, it should only be able to trench/"blast" things that a pickaxe can't... Normally break.

Your blacklist works for 100k blacklisting the breaking of said blocks, but not the intended effect.

Both her and I, and potentially a significant amount of other people want it so we have the option of where your pickaxe mass-breaks only things that can be broken using a pickaxe (Or at least conventionally speaking), and a spade/axe just the same.

The plugin itself is amazing, but I have asked questions like this previously in the discord, but I was greeted with a... Disturbing silence. It's sad that, at this point, this seems to be the best way to report bugs/issues, that will consistently get seen in a periodic way. at least, answered 100% of the time.

**Comment by GC-spigot** [comment]
Simply because I don't respond on discord does not make it that I ignore questions like these. What's your issue with the filter? There's no technical way of me making this exact request other than going through all available materials and marking which one is breakable and which one isn't, which isn't a good way to spend probably over an hour right out of the box and having to go through them all again after minecraft updates when I could be working on more important features.

Flaw with this and automating it with code: every block that is breakable can be broken using a pickaxe, so no way to check if it's a 'pickaxe' breakable block or 'axe' without doing this list. Most if not all CE plugins do trenching the way I do right now and it seems like the industry standard. 

Not every feature asked here is going to be added but every is considered. I can leave this pending but until there's a good way to properly do it, only way to achieve this is with the current filter implementation (not even talking about how material names for blocks change every few versions, which would also be a huge hassle of time investment, using common sense `time per usage` is just not worth on such feature IMO)
