### ISSUE TITLE
%is headshot% is always true for charged shots

### ISSUE THREAD

**Issue by sh1mrr4** [GC-spigot/AdvancedEnchantments#671]
Hey GC,

we experienced an issue with the %is headshot% detection. Basically, if the bow is fully charged, enchantments like Sniper or Lethal Sniper always trigger, even if the target is hit somewhere else. It seems to work as intended for weak shots though.

For demonstration, here is a short video:
[https://www.youtube.com/watch?v=qd0RaDb9AJE&feature=youtu.be](https://www.youtube.com/watch?v=qd0RaDb9AJE&feature=youtu.be)

I adjusted cooldown, chance and message output for this test:
![grafik](https://user-images.githubusercontent.com/47902483/65135504-54dded00-da06-11e9-97d0-df095be7b3d5.png)

Plugin versions:
Paper 1.13.2
AdvancedEnchantments 6.1.3

Thanks in advance!

**Comment by GC-spigot** [comment]
Your problem is that you're extremely close to the player, move further by few blocks and it will not false detect arrows. Since there's no way of 'detecting' a headshot, it works by distance-checking to player head, because you are close, plugin detects the arrow close and counts it as a headshot. There's not much to be done about this, I will lower the checked radius by a small margin but being more than few blocks away fixes it.
