### ISSUE TITLE
[BUG] Potion directivity and some bug

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#673]
**1. Potion directivity**

![image](https://user-images.githubusercontent.com/5382252/65264357-fec19480-db40-11e9-99b6-c436c6828496.png)

the POTION happen in self (bug)
Should be in the enemy
also %attacker% bug

only POTION happen

**2.  Preview bug**
Preview some no show %desc% , please check

**3. some Feature request**

add Enchant confirmation

can add a new item
Transfer all AE enchantments on one weapon to another weapon?

**Comment by GC-spigot** [comment]
1st - %victim% IS YOU SINCE DEFENSE IS YOU GETTING ATTACKED, you do not understand basic english, please use translator for those placeholders.
2nd - tried your configuration but the enchant you screenshot-ed and showed that "doesn't work" actually works, regenerate your customcommands.yml as that might be the only issue.
3rd - no confirmation for that is going to be added.
