### ISSUE TITLE
[Issue] Trench Error as of 7.3.3

### ISSUE THREAD

**Issue by FeroxDrood** [GC-spigot/AdvancedEnchantments#949]
**Describe the bug**
Apply fortune to a pickaxe with trench and mine any ore and you will get this error. The only ore that works in coal. The dupe glitch is fixed atleast lol, also excavation still affect every block rather than just the block the tool you are using can mine.

**Screenshots / Video**
https://pastebin.com/GZWA2hW3
Along with this message in chat.
![image](https://user-images.githubusercontent.com/37503543/79440395-d95d1200-7fcd-11ea-8333-bc766e69fd43.png) (I changed my trench enchant to be called excavation)

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.15.2
- Plugin Version 3.7.7

**Comment by FeroxDrood** [comment]
Also it is still giving stone from Diorite and all those other stone types

**Comment by GC-spigot** [comment]
Sorry about this, fixed the first issue. Second's issue fix is coming when new materials are supported (durability as a data for blocks has been removed) and diorite material was added - but due to how spigot now works my plugin doesn't see that material unless I remove support for <1.13 versions. This fix is coming soon.
