### ISSUE TITLE
Upvote Feature Requests

### ISSUE THREAD

**Issue by GC-spigot** [GC-spigot/AdvancedEnchantments#990]
Introducing new voting system for Feature Requests

**Use the 'Thumbs Up' 👍 Emoji if you want to see a Feature Implemented**
![Upvote](https://i.imgur.com/oQvN7qY.png)

This will drive decisions towards what is popular and what isn't which allows more prominent features to be added sooner. 

This does mean that some more specific requests which may not benefit a broad spectrum will be denied in order to help organize features by priority, as have been said in #1 - _"Do not post requests that may only benefit you and no on else"_. Our goal as a community is to benefit as many as possible and this new change will help me properly assign time for most popular features.

**You can see current most popular requests here:** https://github.com/GC-spigot/AdvancedEnchantments/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by ZeddyOG** [comment]
Maybe have the system utilize both 'Thumbs Up' 👍 and 'Thumbs Down' 👎.

A person could decide whether or not it is a community idea and react with 👍 if they believe it is or react with 👎 if they believe it's not. In my opinion this would make it a better system as you will have both positive and negative feedback rather than just positive.
